### ISSUE TITLE
Crashes when attempting to flatten Modfest 1.15

### ISSUE THREAD

**Issue by TwilightFlower** [shedaniel/ModPackFlattener#1]
yeah, title. trying to get it into a dev env because memory leak, and uh
```Exception in thread "main" java.lang.RuntimeException: Failed to load jar: azuma-1.2.1-beta.jar
        at me.shedaniel.modflattener.MainKt.countJar(Main.kt:264)
        at me.shedaniel.modflattener.MainKt.flatten(Main.kt:41)
        at me.shedaniel.modflattener.MainKt.main(Main.kt:24)
        at me.shedaniel.modflattener.MainKt.main(Main.kt)
Caused by: java.io.FileNotFoundException: C:\nospaces\jars\.removejij\cardinal-components-entity\1586301856030 1584928166000 azuma-1.2.1-beta.jar -> 03faf209-c0d3-4fd3-bb5f-0a30e9b8c07f cardinal-components-entity-2.3.3.jar (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at me.shedaniel.modflattener.MainKt.countJar(Main.kt:260)
        ... 3 more
```
It looks like a bunch of random stuff is ending up in the filename somehow?

**Comment by shedaniel** [comment]
is it possible to send me the modfest modpack

**Comment by shedaniel** [comment]
The numbers in front are just the time of the files, 1586301856030 being the time of zauma and 1584928166000 being the time of cardinal-components-entity. I will remove them in the next update as they are just there for debugging.

I have looked into some issues about this FileNotFoundException (The filename, directory name, or volume label syntax is incorrect), and find out that windows might have limited the length of paths, which might be the problem causing this.

Please try 0.2.3, where I am trying to solve this issue.

**Comment by shedaniel** [comment]
Please try 0.2.4, which properly closed streams, I have tried this version in a windows vm.
